[package]
edition = "2018"
name = "builder-swc"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0"
backtrace = "0.3"
napi = { version = "1", features = ["serde-json"] }
napi-derive = "1"
serde = "1"
serde_json = "1"
swc = "0.66.1"
swc_atoms = "0.2.7"
swc_common = { version = "0.13.3", features = ["concurrent", "sourcemap"] }
swc_node_base = "0.4.0"
swc_ecmascript = { version = "0.72.1", features = ["codegen", "minifier", "optimization", "parser", "react", "transforms", "typescript", "utils", "visit"] }
swc_ecma_preset_env = "0.51.1"
fxhash= "0.2"

[dev-dependencies]
swc_ecma_transforms_testing = "0.36.1"
testing = "0.14.1"

[build-dependencies]
napi-build = "1"

[profile.release]
lto = true
