[package]
edition = "2018"
name = "builder-swc"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0"
backtrace = "0.3"
napi = { version = "1", features = ["serde-json"] }
napi-derive = "1"
serde = "1"
serde_json = "1"
swc = "0.53.0"
swc_atoms = "0.2.6"
swc_common = { version = "0.12.0", features = ["tty-emitter", "sourcemap"] }
swc_node_base = "0.3.0"
swc_ecmascript = { version = "0.63.1", features = ["codegen", "optimization", "parser", "react", "transforms", "typescript", "utils", "visit"] }
swc_ecma_preset_env = "0.42.1"

[dev-dependencies]
swc_ecma_transforms_testing = "0.24.0"
testing = "0.12.0"

[build-dependencies]
napi-build = "1"

[profile.release]
lto = true
