
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes
  branches:
    - "master"

coverage:
  status:
    project:
      default:
        threshold: 90%
    patch: off
