/**
 * 定义应用路由
 */
import React from 'react';
import { Router, hashHistory } from 'react-router';

// 路由配置规则参考： https://github.com/ReactTraining/react-router/blob/v3/docs/guides/RouteConfiguration.md#configuration-with-plain-routes
// <!-- auto generated routes start -->
import Home from './pages/Home';

const autoGeneratedRoutes = [];

// <!-- auto generated routes end -->

// 自定义路由，如果 path 相同则会覆盖自动生成部分的路由配置
const customRoutes = [
  {
    path: '/',
    indexRoute: { component: Home },
  },
];

export default (
  <Router
    history={hashHistory}
    routes={[...autoGeneratedRoutes, ...customRoutes]}
  />
);
