const data = {
  clientSDK: [
    {
      img: require('./images/img1.png'),
      title: '淘宝交易',
      desc: '快速搭建交易闭环',
      androidSDK: 'https://www.taobao.com',
      iosSDK: 'https://www.taobao.com',
      version: '',
      docs: '',
      guide: '',
      faq: '',
    },
    {
      img: require('./images/img2.png'),
      title: '淘宝交易',
      desc: '快速搭建交易闭环',
      androidSDK: 'https://www.taobao.com',
      iosSDK: 'https://www.taobao.com',
      version: '',
      docs: '',
      guide: '',
      faq: '',
    },
    {
      img: require('./images/img3.png'),
      title: '淘宝交易',
      desc: '快速搭建交易闭环',
      androidSDK: 'https://www.taobao.com',
      iosSDK: 'https://www.taobao.com',
      version: '',
      docs: '',
      guide: '',
      faq: '',
    },
    {
      img: require('./images/img1.png'),
      title: '淘宝交易',
      desc: '快速搭建交易闭环',
      androidSDK: 'https://www.taobao.com',
      iosSDK: 'https://www.taobao.com',
      version: '',
      docs: '',
      guide: '',
      faq: '',
    },
    {
      img: require('./images/img2.png'),
      title: '淘宝交易',
      desc: '快速搭建交易闭环',
      androidSDK: 'https://www.taobao.com',
      iosSDK: 'https://www.taobao.com',
      version: '',
      docs: '',
      guide: '',
      faq: '',
    },
    {
      img: require('./images/img3.png'),
      title: '淘宝交易',
      desc: '快速搭建交易闭环',
      androidSDK: 'https://www.taobao.com',
      iosSDK: 'https://www.taobao.com',
      version: '',
      docs: '',
      guide: '',
      faq: '',
    },
  ],
  serverSDK: [
    {
      img: require('./images/img1.png'),
      title: '天猫交易',
      desc: '快速搭建交易闭环',
      androidSDK: 'https://www.taobao.com',
      iosSDK: 'https://www.taobao.com',
      version: '',
      docs: '',
      guide: '',
      faq: '',
    },
    {
      img: require('./images/img2.png'),
      title: '天猫交易',
      desc: '快速搭建交易闭环',
      androidSDK: 'https://www.taobao.com',
      iosSDK: 'https://www.taobao.com',
      version: '',
      docs: '',
      guide: '',
      faq: '',
    },
    {
      img: require('./images/img3.png'),
      title: '天猫交易',
      desc: '快速搭建交易闭环',
      androidSDK: 'https://www.taobao.com',
      iosSDK: 'https://www.taobao.com',
      version: '',
      docs: '',
      guide: '',
      faq: '',
    },
    {
      img: require('./images/img1.png'),
      title: '天猫交易',
      desc: '快速搭建交易闭环',
      androidSDK: 'https://www.taobao.com',
      iosSDK: 'https://www.taobao.com',
      version: '',
      docs: '',
      guide: '',
      faq: '',
    },
    {
      img: require('./images/img2.png'),
      title: '天猫交易',
      desc: '快速搭建交易闭环',
      androidSDK: 'https://www.taobao.com',
      iosSDK: 'https://www.taobao.com',
      version: '',
      docs: '',
      guide: '',
      faq: '',
    },
    {
      img: require('./images/img3.png'),
      title: '天猫交易',
      desc: '快速搭建交易闭环',
      androidSDK: 'https://www.taobao.com',
      iosSDK: 'https://www.taobao.com',
      version: '',
      docs: '',
      guide: '',
      faq: '',
    },
  ],
};

export default data;
