// Keys of appConfig  need transform to manifest.
export const decamelizeKeys = [
  'name',
  'startUrl',
  'shortName',
  'lang',
  'dir',
  'description',
  'backgroundColor',
  'display',
  'icons',
  'appWorker',
  'window',
  'pageHeader',
  'tabHeader',
  'tabBar',
  'pages',
  'dataPrefetch',
  'spm',
  'metas',
  'links',
  'scripts',
  'offlineResources',
  'packageResources',
  'manifestPrefetchExpires',
  'manifestPrefetchMaxAge',
  'maxAge',
  'expires',
  'queryParamsPassKeys',
  'queryParamsPassIgnoreKeys',
  'splashViewTimeout',
  'splashViewAutoClose',
  'splashViewHtml',
  'splashViewUrl',
  'swiperThreshold',
  'requestHeaders',
  'enablePoplayer',
  'disableCapture',
  'enablePullRefresh',
  'pullRefreshBackgroundColor',
  'pullRefreshColorScheme',
  'pullRefresh',
  'cacheQueryParams',
  'customDataSource',
];

// Do not decamelize list.
export const camelizeKeys = [
  'appKey',
  'dataType',
  'valueType',
  'isSec',
  'LoginRequest',
  'sessionOption',
  'AntiCreep',
  'AntiFlood',
  'needLogin',
];

export const validPageConfigKeys = [
  'pageHeader',
  'defaultFrameIndex',
  'title',
  'priority',
  'titleImage',
  'titleBarColor',
  'backgroundColor',
  'enablePullRefresh',
  'external',
  'requestHeaders',
  'frames',
  'dataPrefetch',
  'spm',
  'queryParams',
  'queryParamsPassKeys',
  'queryParamsPassIgnoreKeys',
];

export const templateFile = '.ice/pha-manifest.ts';