import Vue from 'vue';
import Router from 'vue-router';

// 一下部分是由 Iceworks 相关工具自动生成的路由，请勿随意改变，否则可能会出现一些异常情况
// <!-- auto generated routes start -->
import BlankLayout from './layouts/BlankLayout';
import Home from './views/Home.vue';
import About from './views/About.vue';

const autoGeneratedRoutes = {
  routes: [
    {
      path: '/',
      name: 'home',
      component: BlankLayout,
      children: [
        {
          path: '',
          component: Home,
        },
      ],
    },
    {
      path: '/about',
      name: 'about',
      component: BlankLayout,
      children: [
        {
          path: '',
          component: About,
        },
      ],
    },
  ],
};

// <!-- auto generated routes end -->

// 自定义路由，如果 path 相同则会覆盖自动生成部分的路由配置
const customRoutes = {
  routes: [],
};

Vue.use(Router);

export default new Router({
  ...autoGeneratedRoutes,
  ...customRoutes,
  routes: [...autoGeneratedRoutes.routes, ...customRoutes.routes],
});
