const data = [
  {
    id: 1,
    name: 'GetUserId',
    desc: '获取用户身份',
    language: 'NodeJS 8.x',
    skill: '无',
    status: '已发布',
  },
  {
    id: 2,
    name: 'GetUserProfile',
    desc: '获取用户信息',
    language: 'NodeJS 8.x',
    skill: '无',
    status: '已发布',
  },
  {
    id: 3,
    name: 'PostUserLogin',
    desc: '获取用户登录信息',
    language: 'NodeJS 8.x',
    skill: '无',
    status: '已发布',
  },
  {
    id: 4,
    name: 'PostUserRegister',
    desc: '获取用户注册信息',
    language: 'NodeJS 8.x',
    skill: '无',
    status: '已发布',
  },
  {
    id: 5,
    name: 'PostUserLogout',
    desc: '获取用户登出信息',
    language: 'NodeJS 8.x',
    skill: '无',
    status: '已发布',
  },
  {
    id: 6,
    name: 'GetUserId',
    desc: '获取用户身份',
    language: 'NodeJS 8.x',
    skill: '无',
    status: '已发布',
  },
  {
    id: 7,
    name: 'GetUserProfile',
    desc: '获取用户信息',
    language: 'NodeJS 8.x',
    skill: '无',
    status: '已发布',
  },
  {
    id: 8,
    name: 'PostUserLogin',
    desc: '获取用户登录信息',
    language: 'NodeJS 8.x',
    skill: '无',
    status: '已发布',
  },
  {
    id: 9,
    name: 'PostUserRegister',
    desc: '获取用户注册信息',
    language: 'NodeJS 8.x',
    skill: '无',
    status: '已发布',
  },
  {
    id: 10,
    name: 'PostUserLogout',
    desc: '获取用户登出信息',
    language: 'NodeJS 8.x',
    skill: '无',
    status: '已发布',
  },
];

export default data;
