export default {
  'en-us': {
    barText: 'Blog',
    postsTitle: 'All posts',
    list: [
      {
        title: 'The first blog',
        author: 'author1',
        dateStr: 'May 12nd，2018',
        desc: 'Blog description, some text to sum up the main content of the blog',
        link: '/en-us/blog/blog1.html',
      },
      {
        title: 'The second blog',
        author: 'author2',
        dateStr: 'May 2nd，2018',
        desc: 'Blog description, some text to sum up the main content of the blog',
        link: '/en-us/blog/blog2.html',
      },
      {
        title: 'The third blog',
        author: 'author3',
        dateStr: 'April 25th，2018',
        desc: 'Blog description, some text to sum up the main content of the blog',
        link: '/en-us/blog/blog3.html',
      },
      {
        title: 'The forth blog',
        author: 'author4',
        dateStr: 'April 22nd，2018',
        desc: 'Blog description, some text to sum up the main content of the blog',
        link: '/en-us/blog/blog4.html',
      },
      {
        title: 'The fifth blog',
        author: 'author5',
        dateStr: 'April 22nd，2018',
        desc: 'Blog description, some text to sum up the main content of the blog',
        link: '/en-us/blog/blog5.html',
      },
      {
        title: 'The sixth blog',
        author: 'author6',
        dateStr: 'April 22nd，2018',
        desc: 'Blog description, some text to sum up the main content of the blog',
        link: '/en-us/blog/blog6.html',
      },
      {
        title: 'The seventh blog',
        author: 'author7',
        dateStr: 'April 22nd，2018',
        desc: 'Blog description, some text to sum up the main content of the blog',
        link: '/en-us/blog/blog7.html',
      },
    ],
  },
  'zh-cn': {
    barText: '博客',
    postsTitle: '所有文章',
    list: [
      {
        title: '第一篇博客',
        author: 'author1',
        dateStr: 'May 12nd，2018',
        desc: '博客描述，总结博客的主体内容',
        link: '/zh-cn/blog/blog1.html',
      },
      {
        title: '第二篇博客',
        author: 'author2',
        dateStr: 'May 2nd，2018',
        desc: '博客描述，总结博客的主体内容',
        link: '/zh-cn/blog/blog2.html',
      },
      {
        title: '第三篇博客',
        author: 'author3',
        dateStr: 'April 25th，2018',
        desc: '博客描述，总结博客的主体内容',
        link: '/zh-cn/blog/blog3.html',
      },
      {
        title: '第四篇博客',
        author: 'author4',
        dateStr: 'April 22nd，2018',
        desc: '博客描述，总结博客的主体内容',
        link: '/zh-cn/blog/blog4.html',
      },
      {
        title: '第五篇博客',
        author: 'author5',
        dateStr: 'April 22nd，2018',
        desc: '博客描述，总结博客的主体内容',
        link: '/zh-cn/blog/blog5.html',
      },
      {
        title: '第六篇博客',
        author: 'author6',
        dateStr: 'April 22nd，2018',
        desc: '博客描述，总结博客的主体内容',
        link: '/zh-cn/blog/blog6.html',
      },
      {
        title: '第七篇博客',
        author: 'author7',
        dateStr: 'April 22nd，2018',
        desc: '博客描述，总结博客的主体内容',
        link: '/zh-cn/blog/blog7.html',
      },
    ],
  },
};
