/**
 * 按照下载量和最新的规则对模板进行排序推荐
 */
const scaffolds = [
  'ice-customer-analysis-admin',
  'ice-voice-chat-admin',
  'ice-library-management-admin',
  'ice-asset-management-admin',
  'ice-application-management-admin',
  'ice-task-management-admin',
  'ice-government-management-admin',
  'ice-monitor-dashboard',
  'ice-algorithm-model-admin',
  'ice-contract-management-admin',
  'ice-usertrack-admin',
  'ice-yunqi-homepage',
  'ice-scroll-screen-homepage',
  'ice-builder-platform',
  'ice-design-pro',
  'ice-design-cms',
  'ice-design-analysis',
  'ice-design-schools',
  'ice-design-lite',
  'ice-post-platfrom',
  'ice-light-bootstrap-dashboard',
  'ice-reviews-management',
  'ice-creative-dashboard',
  'ice-coreui-admin',
  'ice-material-dashboard',
  'ice-design-dashboard',
  'ice-design-hospital',
  'ice-design-ecommerce',
  'ice-design-project-management',
  'ice-website-homepage',
  'iceworks-homepage',
  'ice-creator-landingpage',
  'ice-open-platform-landingpage',
  'ice-operation-platform',
  'create-react-app',
  'ice-opensource-site',
];

module.exports = scaffolds;
