/**
 * 定义应用路由
 */
import React from 'react';
import {
  Router, Route, Redirect, IndexRoute, IndexRedirect,
  // browserHistory,
  hashHistory
} from 'react-router';

import HeaderAsideFooterLayout from './layouts/HeaderAsideFooterLayout';
import Home from './pages/Home';
import Dashboard from './pages/Dashboard';
import Charts from './pages/Charts';
import Table from './pages/Table';
import List from './pages/List';
import Portlets from './pages/Portlets';
import Result from './pages/Result';
import Fail from './pages/Fail';
import FixedHeaderFooterResponsiveLayout from './layouts/FixedHeaderFooterResponsiveLayout';
import Landing from './pages/Landing';
import IceworksPreviewPage from './pages/IceworksPreviewPage';

// 以下部分是由 ICE 相关工具自动生成的路由，请勿随意改变，否则可能会出现一些异常情况
// ---auto generated routes start---
const autoGeneratedRoutes = [ { path: '/IceworksPreviewPage',
    childRoutes: [],
    component: FixedHeaderFooterResponsiveLayout,
    indexRoute: { component: IceworksPreviewPage } },
  { path: '/landing',
    childRoutes: [],
    component: FixedHeaderFooterResponsiveLayout,
    indexRoute: { component: Landing } },
  { path: '/result',
    childRoutes: 
     [ { path: 'success', childRoutes: [], component: Result },
       { path: 'fail', childRoutes: [], component: Fail } ],
    component: HeaderAsideFooterLayout,
    indexRoute: { component: Result } },
  { path: '/portlets',
    childRoutes: [],
    component: HeaderAsideFooterLayout,
    indexRoute: { component: Portlets } },
  { path: '/list',
    childRoutes: [],
    component: HeaderAsideFooterLayout,
    indexRoute: { component: List } },
  { path: '/complex',
    childRoutes: [],
    component: HeaderAsideFooterLayout,
    indexRoute: { component: Table } },
  { path: '/charts',
    childRoutes: [],
    component: HeaderAsideFooterLayout,
    indexRoute: { component: Charts } },
  { path: '/dashboard',
    childRoutes: [],
    component: HeaderAsideFooterLayout,
    indexRoute: { component: Dashboard } },
  { path: '/',
    childRoutes: [],
    component: HeaderAsideFooterLayout,
    indexRoute: { component: Home } } ];
// ---auto generated routes end---

// 自定义路由，如果 path 相同则会覆盖自动生成部分的路由配置
const customRoutes = [];

export default (
  <Router
    history={hashHistory}
    routes={[...autoGeneratedRoutes, ...customRoutes]}
  />
);
