/**
 * 定义应用路由
 */
import React from 'react';
import {
  Router, Route, Redirect, IndexRoute, IndexRedirect,
  // browserHistory,
  hashHistory,
} from 'react-router';

import HeaderAsideFooterLayout from './layouts/HeaderAsideFooterLayout';
import Dashboard from './pages/Dashboard';
import Charts from './pages/Charts';
import Portlets from './pages/Portlets';
import Terms from './pages/Terms';
import ProgressInfo from './pages/ProgressInfo';
import Result from './pages/Result';
import Fail from './pages/Fail';
import FixedHeaderFooterResponsiveLayout from './layouts/FixedHeaderFooterResponsiveLayout';
import Landing from './pages/Landing';
import ServerError from './pages/ServerError';
import NotFound from './pages/NotFound';
import NotPermission from './pages/NotPermission';
import EmptyContent from './pages/EmptyContent';
import List from './pages/List';
import CardList from './pages/CardList';
import PicturesList from './pages/PicturesList';
import BasicTable from './pages/BasicTable';
import TableList from './pages/TableList';
import TableDisplay from './pages/TableDisplay';

// 以下部分是由 ICE 相关工具自动生成的路由，请勿随意改变，否则可能会出现一些异常情况
// ---auto generated routes start---
const autoGeneratedRoutes = [
  {
    path: '/table',
    childRoutes:
      [{
        path: 'basic-table',
        childRoutes: [],
        component: BasicTable,
      },
      {
        path: 'table-list',
        childRoutes: [],
        component: TableList,
      },
      {
        path: 'table-display',
        childRoutes: [],
        component: TableDisplay,
      }],
    component: HeaderAsideFooterLayout,
    indexRoute: { component: BasicTable },
  },
  {
    path: '/list',
    childRoutes:
      [{ path: 'article-list', childRoutes: [], component: List },
        { path: 'card-list', childRoutes: [], component: CardList },
        {
          path: 'picture-list',
          childRoutes: [],
          component: PicturesList,
        }],
    component: HeaderAsideFooterLayout,
    indexRoute: { component: List },
  },
  {
    path: '/exception',
    childRoutes:
      [{ path: '500', childRoutes: [], component: ServerError },
        { path: '404', childRoutes: [], component: NotFound },
        { path: '403', childRoutes: [], component: NotPermission },
        { path: 'empty', childRoutes: [], component: EmptyContent }],
    component: HeaderAsideFooterLayout,
    indexRoute: { component: ServerError },
  },
  {
    path: '/result',
    childRoutes:
      [{ path: 'success', childRoutes: [], component: Result },
        { path: 'fail', childRoutes: [], component: Fail }],
    component: HeaderAsideFooterLayout,
    indexRoute: { component: Result },
  },
  {
    path: '/portlets',
    childRoutes:
      [{ path: 'base', childRoutes: [], component: Portlets },
        { path: 'terms', childRoutes: [], component: Terms },
        {
          path: 'progress',
          childRoutes: [],
          component: ProgressInfo,
        }],
    component: HeaderAsideFooterLayout,
    indexRoute: { component: Portlets },
  },
  {
    path: '/chart',
    childRoutes: [{ path: 'chart-list', childRoutes: [], component: Charts }],
    component: HeaderAsideFooterLayout,
    indexRoute: { component: Charts },
  },
  {
    path: '/dashboard',
    childRoutes: [],
    component: HeaderAsideFooterLayout,
    indexRoute: { component: Dashboard },
  },
  {
    path: '/',
    childRoutes: [],
    component: FixedHeaderFooterResponsiveLayout,
    indexRoute: { component: Landing },
  }];
// ---auto generated routes end---

// 自定义路由，如果 path 相同则会覆盖自动生成部分的路由配置
const customRoutes = [];

export default (
  <Router
    history={hashHistory}
    routes={[...autoGeneratedRoutes, ...customRoutes]}
  />
);
