name: Beta Publisher

on:
  push:
    branches:
      - beta

jobs:
  build-and-publish-beta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: https://registry.npmjs.org/
      - run: npm run setup
      - run: npm run publish:beta
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          ACCESS_KEY_SECRET: ${{ secrets.ACCESS_KEY_SECRET }}
          REGISTRY: https://registry.npmjs.org
